#!/bin/bash
mysql -u root -p"${MYSQL_ROOT_PASSWORD}" "${MYSQL_DATABASE}" <<EOF
CREATE USER IF NOT EXISTS '${DB_RESTRICTED_USER}'@'%' IDENTIFIED BY '${DB_RESTRICTED_PASS}';
GRANT SELECT, INSERT ON ${MYSQL_DATABASE}.* TO '${DB_RESTRICTED_USER}'@'%';

CREATE USER IF NOT EXISTS '${DB_ADMIN_USER}'@'%' IDENTIFIED BY '${DB_ADMIN_PASS}';
GRANT ALL PRIVILEGES ON ${MYSQL_DATABASE}.* TO '${DB_ADMIN_USER}'@'%';

FLUSH PRIVILEGES;
EOF